<?php
/*
Template Name: Terms & Conditions
*/
get_header(); ?>

<style>
:root{--lp-maroon:#6B2737;--lp-maroon-dk:#4A0E1A;--lp-gold:#C9A055;--lp-cream:#FFF8F0;--lp-border:#E8DDD0;--lp-text:#3A2A20;--lp-muted:#666;}
.lp-page{background:var(--lp-cream);min-height:100vh;}

/* HERO */
.lp-hero{background:linear-gradient(135deg,var(--lp-maroon-dk) 0%,var(--lp-maroon) 60%,#8B3045 100%);padding:70px 24px 90px;text-align:center;position:relative;overflow:hidden;}
.lp-hero-bg{position:absolute;inset:0;background:url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none'%3E%3Cg fill='%23ffffff' fill-opacity='0.03'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");pointer-events:none;}
.lp-hero-inner{position:relative;z-index:1;max-width:700px;margin:0 auto;}
.lp-eyebrow{display:inline-block;font-size:.68rem;font-weight:700;letter-spacing:3px;text-transform:uppercase;color:#F5C842;background:rgba(201,160,85,.2);border:1px solid rgba(201,160,85,.35);padding:5px 16px;border-radius:30px;margin-bottom:16px;}
.lp-hero h1{font-family:'Playfair Display',Georgia,serif;font-size:clamp(2rem,5vw,3.2rem);color:#fff;font-weight:700;line-height:1.2;margin-bottom:12px;}
.lp-hero p{color:rgba(255,255,255,.8);font-size:.95rem;line-height:1.7;}
.lp-hero-wave{position:absolute;bottom:-1px;left:0;right:0;}
.lp-hero-wave svg{display:block;width:100%;height:50px;}

/* BODY */
.lp-body{max-width:860px;margin:0 auto;padding:60px 24px 100px;}

/* Sections */
.lp-section{margin-bottom:48px;}
.lp-section-title{font-family:'Playfair Display',Georgia,serif;font-size:1.35rem;font-weight:700;color:var(--lp-maroon);margin-bottom:8px;padding-bottom:10px;border-bottom:2px solid var(--lp-border);display:flex;align-items:center;gap:10px;}
.lp-section-title svg{width:20px;height:20px;color:var(--lp-gold);flex-shrink:0;}
.lp-section p{font-size:.93rem;color:var(--lp-muted);line-height:1.85;margin-bottom:12px;}
.lp-section p:last-child{margin-bottom:0;}
.lp-section strong{color:var(--lp-text);}
.lp-section a{color:var(--lp-maroon);font-weight:600;}
.lp-section a:hover{color:var(--lp-gold);}

/* Notice box */
.lp-notice{background:rgba(107,39,55,.06);border-left:4px solid var(--lp-maroon);border-radius:0 10px 10px 0;padding:16px 20px;margin-bottom:28px;font-size:.88rem;color:var(--lp-text);line-height:1.7;font-weight:500;}

/* Contact card */
.lp-contact-card{background:#fff;border:1.5px solid var(--lp-border);border-radius:16px;padding:24px 28px;margin-top:40px;}
.lp-contact-card h3{font-family:'Playfair Display',Georgia,serif;font-size:1.2rem;color:var(--lp-maroon);margin-bottom:14px;}
.lp-contact-row{display:flex;align-items:center;gap:10px;font-size:.88rem;color:var(--lp-muted);margin-bottom:8px;}
.lp-contact-row svg{width:16px;height:16px;color:var(--lp-gold);flex-shrink:0;}
.lp-contact-row strong{color:var(--lp-text);min-width:100px;}

@media(max-width:600px){.lp-body{padding:40px 16px 70px;}.lp-hero{padding:55px 16px 80px;}}
</style>

<main class="lp-page">

<div class="lp-hero">
  <div class="lp-hero-bg"></div>
  <div class="lp-hero-inner">
    <span class="lp-eyebrow">Legal</span>
    <h1>Terms &amp; Conditions</h1>
    <p>Please read these terms carefully before using the Hombisilu platform.</p>
  </div>
  <div class="lp-hero-wave"><svg viewBox="0 0 1440 60" preserveAspectRatio="none"><path d="M0,40 C360,80 1080,0 1440,40 L1440,60 L0,60 Z" fill="#FFF8F0"/></svg></div>
</div>

<div class="lp-body">

  <div class="lp-notice">
    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011.
  </div>

  <div class="lp-section">
    <div class="lp-section-title">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="10"/><path d="M12 8h.01M12 12v4"/></svg>
      About the Platform
    </div>
    <p>The Platform is owned by a company incorporated under the Companies Act, 1956, with its registered office at <strong>12, Somashettihalli, Chikkabanavara, Bengaluru</strong> (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').</p>
    <p>The Platform is accessible at the domain name <strong>www.hombisilu.com</strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>
  </div>

  <div class="lp-section">
    <div class="lp-section-title">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
      Acceptance of Terms
    </div>
    <p>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.</p>
    <p>By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services').</p>
    <p>Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. <strong>These Terms of Use can be modified at any time without assigning any reason.</strong> It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>
    <p>For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>
    <p><strong>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</strong></p>
  </div>

  <div class="lp-section">
    <div class="lp-section-title">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
      Terms of Use
    </div>
    <p>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
    <p>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
    <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
    <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
    <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
    <p>You agree to pay us the charges associated with availing the Services.</p>
    <p>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
    <p>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.</p>
    <p>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>
  </div>

  <div class="lp-section">
    <div class="lp-section-title">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75"/></svg>
      Indemnification
    </div>
    <p>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>
  </div>

  <div class="lp-section">
    <div class="lp-section-title">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 22V12M12 12L7 7M12 12l5-5"/><circle cx="12" cy="5" r="3"/></svg>
      Force Majeure
    </div>
    <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>
  </div>

  <div class="lp-section">
    <div class="lp-section-title">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 010 20M12 2a15.3 15.3 0 000 20"/></svg>
      Governing Law &amp; Jurisdiction
    </div>
    <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the <strong>laws of India</strong>.</p>
    <p>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in India.</p>
    <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>
  </div>

  <!-- Contact card -->
  <div class="lp-contact-card">
    <h3>Contact &amp; Grievance Officer</h3>
    <div class="lp-contact-row">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
      <strong>Name:</strong> Mr. Pratham Kumar
    </div>
    <div class="lp-contact-row">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2"/><path d="M16 21V5a2 2 0 00-2-2h-4a2 2 0 00-2 2v16"/></svg>
      <strong>Designation:</strong> Proprietor
    </div>
    <div class="lp-contact-row">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg>
      <strong>Company:</strong> SGR Manufacturing and Trading
    </div>
    <div class="lp-contact-row">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 16.92v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07A19.5 19.5 0 013.07 9.82 19.79 19.79 0 01.19 1.22 2 2 0 012.2 0h3a2 2 0 012 1.72c.127.96.361 1.903.7 2.81a2 2 0 01-.45 2.11L6.91 7.09a16 16 0 006 6l.46-.46a2 2 0 012.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0122 14.92z"/></svg>
      <strong>Phone:</strong> <a href="tel:+916362616933">+91 6362616933</a> &nbsp;(Mon–Fri, 9:00–18:00)
    </div>
    <div class="lp-contact-row">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
      <strong>Email:</strong> <a href="mailto:hombisilufooods@gmail.com">hombisilufooods@gmail.com</a>
    </div>
  </div>

</div>
</main>

<?php get_footer(); ?>
