<?php
/*
Template Name: Terms & Conditions
*/
get_header(); ?>

<main class="lp-page">

<!-- ══════════════════════════════════════════
     PAGE HEAD
══════════════════════════════════════════ -->
<section class="ds-pagehead">
  <div class="ds-wrap">
    <nav class="ds-crumbs" aria-label="Breadcrumb">
      <a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a>
      <?php echo hb_icon( 'chev', 12 ); ?>
      <span aria-current="page">Terms &amp; Conditions</span>
    </nav>

    <span class="ds-eyebrow">Legal</span>
    <h1 class="ds-pagehead-title">Terms &amp; Conditions</h1>
    <p class="ds-sub">Please read these terms carefully before using the Hombisilu platform.</p>
  </div>
</section>

<!-- ══════════════════════════════════════════
     BODY
══════════════════════════════════════════ -->
<section class="ds-section ds-section--cream">
  <div class="ds-wrap ds-wrap--narrow">
    <div class="ds-prose">

      <p class="lp-notice">
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011.
      </p>

      <h2>About the Platform</h2>
      <p>The Platform is owned by a company incorporated under the Companies Act, 1956, with its registered office at <strong>12, Somashettihalli, Chikkabanavara, Bengaluru</strong> (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').</p>
      <p>The Platform is accessible at the domain name <strong>www.hombisilu.com</strong> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>

      <h2>Acceptance of Terms</h2>
      <p>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction.</p>
      <p>By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services').</p>
      <p>Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. <strong>These Terms of Use can be modified at any time without assigning any reason.</strong> It is your responsibility to periodically review these Terms of Use to stay informed of updates.</p>
      <p>For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>
      <p><strong>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</strong></p>

      <h2>Terms of Use</h2>
      <p>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</p>
      <p>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
      <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
      <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
      <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
      <p>You agree to pay us the charges associated with availing the Services.</p>
      <p>You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
      <p>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience to provide further information.</p>
      <p>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</p>

      <h2>Indemnification</h2>
      <p>You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.</p>

      <h2>Force Majeure</h2>
      <p>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</p>

      <h2>Governing Law &amp; Jurisdiction</h2>
      <p>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the <strong>laws of India</strong>.</p>
      <p>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in India.</p>
      <p>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</p>

    </div>

    <div class="ds-card lp-contact">
      <h3>Contact &amp; Grievance Officer</h3>
      <ul class="lp-contact-list">
        <li><span class="lp-contact-label">Name</span><span>Mr. Pratham Kumar</span></li>
        <li><span class="lp-contact-label">Designation</span><span>Proprietor</span></li>
        <li><span class="lp-contact-label">Company</span><span>SGR Manufacturing and Trading</span></li>
        <li><span class="lp-contact-label">Phone</span><span><a href="tel:+916362616933">+91 6362616933</a> &nbsp;(Mon&ndash;Fri, 9:00&ndash;18:00)</span></li>
        <li><span class="lp-contact-label">Email</span><span><a href="mailto:hombisilufooods@gmail.com">hombisilufooods@gmail.com</a></span></li>
      </ul>
    </div>

  </div>
</section>

</main>

<?php get_footer(); ?>
